version: '3.9'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cnc_office
      POSTGRES_USER: cnc_user
      POSTGRES_PASSWORD: cnc_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cnc_user:cnc_password@db:5432/cnc_office

volumes:
  postgres_data:
  media_volume:
