[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
python_files = test_*.py *_tests.py tests_api.py
norecursedirs = .pytest_cache pytest-cache-files-*
addopts = -q --disable-warnings --maxfail=1 --cov=files --cov=documents --cov=sections --cov=users --cov=bot_api --cov=api.xlsx_export --cov-report=term-missing:skip-covered
